version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data:/data/db

  # Backend (Node.js)
  backend:
    image: node:latest
    container_name: backend
    working_dir: /app/backend
    command: npm run build && npm start
    volumes:
      - ./backend:/app/backend
    ports:
      - "3100:3100"
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env

  # Frontend (React)
  frontend:
    image: node:latest
    container_name: frontend
    working_dir: /app/frontend
    command: npm run build && npm start
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./backend/.env

volumes:
  mongodb_data:
